add add and delete for todo
mate-academy/react_todo-app-add-and-delete pull request #1005
Opened 2024-01-03 14:34 UTC by Vlad4567

- [DEMO LINK](https://Vlad4567.github.io/react_todo-app-add-and-delete/)

2024-01-03 16:05 UTC, lerastarynets requested changes
I see you did a hard work) Let's improve it a little bit

2024-01-03 16:05 UTC, lerastarynets commented on src/components/TodoItem/TodoItem.tsx
> +        !editing && hover && (
consider moving long ternaries to separate consts and then use it here

2024-01-03 16:05 UTC, lerastarynets commented on src/components/TodoItem/TodoItem.tsx
> +          </div>
you can create separate Loader component for this

2024-01-04 13:59 UTC, l4st1m0za approved these changes
Good job!

2024-01-04 13:59 UTC, l4st1m0za commented on src/components/TodoItem/TodoItem.tsx
> +  const [editing] = useState(false);
```suggestion
  const [editing, setEditing] = useState(false);
```

2026-08-06 08:05 UTC, closed without merging