add solution of second part
mate-academy/react_todo-app-add-and-delete pull request #1049
Opened 2024-02-02 17:44 UTC by ssaviak

[DEMO LINK](https://ssaviak.github.io/react_todo-app-add-and-delete/)

2024-02-06 13:33 UTC, olya-shyian requested changes
Goood!✨

Also the loader should be each time you add or delete Todos (and in other cases)

Check the working version
![image](https://github.com/mate-academy/react_todo-app-add-and-delete/assets/91946036/15f1f87a-97e2-4500-9ec2-31ef248afec3)

2024-02-06 13:33 UTC, olya-shyian commented on src/App.tsx
> +      <Error />
use check

`{errorMessage && <Error />}`

2024-02-06 13:33 UTC, olya-shyian commented on src/components/Header.tsx
> +    if (query.trim().length === 0) {
instead write 
`(!query.trim().length)`

2024-02-06 13:33 UTC, olya-shyian commented on src/App.tsx
> +    getTodos(84)
please do updates according to comments from previous task

https://github.com/mate-academy/react_todo-app-loading-todos/pull/1115#pullrequestreview-1862804333

2024-02-09 17:35 UTC, DanilWeda requested changes
Great work! 
Check comments about small issues.
Many thanks!

2024-02-09 17:35 UTC, DanilWeda commented on src/contexts/TodoContext.tsx
> +    }),
can move it outside

2024-02-09 17:35 UTC, DanilWeda commented on src/App.tsx
> +      .then((res) => setTodos(res))
or you can write 
```suggestion
      .then(setTodos)
```

2024-02-12 08:19 UTC, olya-shyian approved these changes
Thank you!🌟

2024-05-13 11:23 UTC, closed without merging