1
mate-academy/react_todo-app-add-and-delete pull request #1167
Opened 2024-04-04 16:55 UTC by viktor-kniahnytskyi

[DEMO LINK](https://viktor-kniahnytskyi.github.io/react_todo-app-add-and-delete/)

2024-04-04 17:04 UTC, vadiimvooo requested changes
Well done. You have to deploy your solution. Also please pass all the tests. Feel free to ask for help in fe_chat if you need some.

2024-04-04 17:04 UTC, vadiimvooo commented on src/App.tsx
> +        {!!todos.length && (
```suggestion
        {todos.length && (
```

2024-04-04 17:04 UTC, vadiimvooo commented on src/components/Foofer.tsx
> +      {/* this button should be disabled if there are no completed todos */}
```suggestion
```

2024-04-04 19:37 UTC, vadiimvooo requested changes
Good job. Try to fix the comment and pass the tests. Feel free to ask for help in chat.

2024-04-04 19:37 UTC, vadiimvooo commented on src/components/Foofer.tsx
> +      await Promise.all(completedTodos.map(todo => deleteTodo(todo.id)));
This Promise all can cause test failure, please try to use just for loop and delete every todo individually.

2024-04-05 05:39 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-04-05 05:39 UTC, volodymyr-soltys97 commented on src/App.tsx
> +    }
```suggestion
    switch (status) {
      case Status.Active:
        return !task.completed;
        
      case Status.Completed:
        return task.completed;
        
      case Status.All:
      default:
        return true;
    }
```

2024-04-05 05:39 UTC, volodymyr-soltys97 commented on src/App.tsx
> +  const filteredTodos = todos.filter(task => {
```suggestion
  const filteredTodos = todos.filter(todo => {
```

2024-04-05 05:39 UTC, volodymyr-soltys97 commented on src/App.tsx
> +        {todos.length > 0 && (
```suggestion
        {!!todos.length && (
```

2024-04-05 05:39 UTC, volodymyr-soltys97 commented on src/components/Foofer.tsx
> +        left
Move this checking to the helper variable and use it here

2024-04-05 05:39 UTC, volodymyr-soltys97 commented on src/components/TodoItem.tsx
> +          {todo.title}
Use destruction for `todo`

2024-04-05 05:39 UTC, volodymyr-soltys97 commented on src/components/TodoItem.tsx
> +        className={`modal overlay ${!todo.id || (loading && todo.id === selectedTodo?.id) ? 'is-active' : ''}`}
Use classnames library here for add classes with condition

2024-04-05 05:39 UTC, volodymyr-soltys97 commented on src/components/TodoItem.tsx
> +        }}
Move this logic from jsx to the helper function and use it here

2024-04-05 10:05 UTC, closed without merging