react add and delete api
mate-academy/react_todo-app-add-and-delete pull request #1371
Opened 2024-07-30 20:57 UTC by Fetrw

[DEMO LINK](https://Fetrw.github.io/react_todo-app-add-and-delete/)

2024-07-30 23:47 UTC, GUSILLUS requested changes
GJ!

2024-07-30 23:47 UTC, GUSILLUS commented on src/App.tsx
> +          onClick={() => setError('')}
Consider using handler function here

2024-07-30 23:47 UTC, GUSILLUS commented on src/components/Header/Header.tsx
> +        }}
same

2024-07-30 23:47 UTC, GUSILLUS commented on src/components/TodoFilter/TodoFilter.tsx
> +            onClick={() => setFilter(value)}
same

2024-07-30 23:47 UTC, GUSILLUS commented on src/components/TodoItem/TodoItem.tsx
> +        onDoubleClick={() => setIsEditing(true)}
same

2024-07-31 11:24 UTC, lerastarynets approved these changes
lgtm 🚀

2026-01-16 17:46 UTC, closed without merging