solution
mate-academy/react_todo-app-add-and-delete pull request #140
Opened 2022-12-07 23:10 UTC by 1stIndominus

[DEMO LINK](https://1stIndominus.github.io/react_todo-app-add-and-delete/)

2022-12-08 11:30 UTC, Anastasiia-Svintsova commented on src/App.tsx
> +      .catch(() => isError);
Do you understand what this catch will do? Maybe you need to use `setIsError` here instead?

2022-12-08 11:31 UTC, Anastasiia-Svintsova commented on src/components/ErrorType/ErrorType.tsx
> +/* eslint-disable jsx-a11y/control-has-associated-label */
don't disable eslint

2022-12-08 11:32 UTC, Anastasiia-Svintsova commented on src/components/Footer/Footer.tsx
> +        {`${todos.length - completedTodos.length} items left`}
Let's move `todos.length - completedTodos.length` to a variable

2022-12-08 11:33 UTC, Anastasiia-Svintsova commented on src/components/Footer/Footer.tsx
> +            { 'filter__link selected': filter === 'all' })}
You have the enum for `all` value

2022-12-08 11:33 UTC, Anastasiia-Svintsova commented on src/components/Footer/Footer.tsx
> +            'filter__link selected': filter === 'active',
And for `active`. Use the enum

2022-12-08 11:33 UTC, Anastasiia-Svintsova commented on src/components/Footer/Footer.tsx
> +            'filter__link selected': filter === 'completed',
Same for `completed`

2022-12-08 11:34 UTC, Anastasiia-Svintsova commented on src/components/TodoList/TodoList.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Same about eslint. Check it everywhere

2022-12-10 12:02 UTC, Anastasiia-Svintsova requested changes
- The issue with the loader still exists. You should show the new todo with the loader, not just the loader. Check the [working example](https://mate-academy.github.io/react_todo-app-with-api/). If you have any questions feel free to ask them in the fe_chat.

https://user-images.githubusercontent.com/99403198/206853989-e035c1fc-c62d-439e-be3a-38e120f394e5.mov

2022-12-12 18:40 UTC, loralevitska requested changes
GJ) A little more and it will be completed

2022-12-12 18:40 UTC, loralevitska commented on src/App.tsx
> +      setTodos(prevState => (prevState.map((a) => (a.id === todoId
not fixed yet

2022-12-12 18:40 UTC, loralevitska commented on src/App.tsx
> +      .catch(() => setIsError);
What did you want to express in the code with this entry? Can you explain please?
```suggestion
      .catch((error) => setIsError(error?.message));
```

2022-12-12 18:40 UTC, loralevitska commented on src/App.tsx
> +      .catch(() => setIsError);
I recommend that you repeat [`try {...} catch {...}`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/try...catch)

2022-12-13 09:38 UTC, polosanya requested changes
Good job! I'm approving it, but please pay attention to my comment

2022-12-13 09:38 UTC, polosanya commented on src/App.tsx
> +  const [isError, setIsError] = useState('');
Prefix `is` is usually used in names for boolean values. It can be confusing for other developers to put it for other values

2023-12-06 14:25 UTC, closed without merging