solution
mate-academy/react_todo-app-add-and-delete pull request #1531
Opened 2024-12-17 11:19 UTC by Fridrif27

[DEMO LINK](https://fridrif27.github.io/react_todo-app-add-and-delete/)

2024-12-17 14:54 UTC, Welbrn approved these changes
Good job!

2024-12-19 16:01 UTC, VolodymyrKirichenko requested changes
Good job, but let's offload your main component a bit and improve the code 🥹

2024-12-19 16:01 UTC, VolodymyrKirichenko commented on src/App.tsx
> +export enum Filter {
move all ur enums to separate directory

2024-12-19 16:01 UTC, VolodymyrKirichenko commented on src/App.tsx
> +  const [isSubmiting, setIsSubmiting] = useState<boolean>(false);
1) Create enum for all the error `FiltersType.Default = ''`
2) Create enum for statuses
3) if u set (string, number, logical value) as the initial value - u don't need a generic type for this
```suggestion
  const [query, setQuery] = useState('');
  const [todos, setTodos] = useState<Todo[]>([]);
  const [itemsLeft, setItemsLeft] = useState(0);
  const [sortBy, setSortBy] = useState<FiltersType>(FiltersType.All);
  const [errorMessage, setErrorMessage] = useState<ErrorType>(ErrorType.Default);
  const [deleteTodoId, setDeleteTodoId] = useState<number | null>(null);
  const [isLoadingChange, setIsLoadingChange] = useState(false);
  const [cleanCompleted, setCleanCompleted] = useState(false);
  const [newTask, setNewTask] = useState('');
  const [tempTodo, setTempTodo] = useState<Todo | null>(null);
  const [isSubmiting, setIsSubmiting] = useState(false);
```

2024-12-19 16:01 UTC, VolodymyrKirichenko commented on src/App.tsx
> +    if (query.trim() !== '') {
the same, but more readable

```suggestion
    if (query.trim().length) {
```

2024-12-19 16:01 UTC, VolodymyrKirichenko commented on src/App.tsx
> +  const [deleteTodoId, setDeleteTodoId] = useState<number | null>(null);
do you need this state? Why?
you can get this id in function arguments

2024-12-19 16:01 UTC, VolodymyrKirichenko commented on src/App.tsx
> +    async function deleteTodoFromServer() {
`deleteTodoFromServer` of `deleteTodosFromServer`?

2024-12-19 16:01 UTC, VolodymyrKirichenko commented on src/App.tsx
> +        }
move to separate function

2024-12-31 07:49 UTC, closed without merging