Done
mate-academy/react_todo-app-add-and-delete pull request #190
Opened 2023-01-10 17:09 UTC by p-omogit-e

[DEMO LINK](https://p-mogit-e.github.io/react_todo-app-add-and-delete/)

2023-01-11 08:38 UTC, tetiana-ivanchenko requested changes
add demo link

2023-01-11 08:38 UTC, tetiana-ivanchenko commented on src/api/todos.ts
> +  userId: number | undefined,
```suggestion
  userId?: number,
```

2023-01-11 08:38 UTC, tetiana-ivanchenko commented on src/components/TodoList/TodoList.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
remove eslint-disable

2023-01-11 08:51 UTC, vlad-demchuk requested changes
demo link isn't working

2023-01-11 08:51 UTC, vlad-demchuk commented on src/App.tsx
> +  const findTodos = async () => {
```suggestion
  const fetchTodos = async () => {
```

2023-01-11 08:51 UTC, vlad-demchuk commented on src/App.tsx
> +  const findTodos = async () => {
it will be better than `find`

2023-01-11 08:51 UTC, vlad-demchuk commented on src/App.tsx
> +    const loadedTodos = await getTodos(user?.id) || null;
loadedTodos shouldn't be `null`. use try/catch construction to catch errors

2023-01-11 08:51 UTC, vlad-demchuk commented on src/App.tsx
> +    setVisibleList(todoList);
you don't need `setVisibleList` here. if you do it in cases it will be the same. just use default case correctly

2023-01-11 08:51 UTC, vlad-demchuk commented on src/App.tsx
> +                  setTimeout(cancelErrors, 3000);
create a separate handle function

2023-01-11 08:52 UTC, p-omogit-e commented on src/components/FilterList/FilterLIst.tsx
> +            { selected: filterBy === Filter.active })}
![image](https://user-images.githubusercontent.com/102521367/211760740-7f948fbb-c627-4285-a8f1-9d7b0c2d9181.png)
![image](https://user-images.githubusercontent.com/102521367/211760823-72f1502c-c36b-42f9-aa61-fdfbc45d85b0.png)

2023-01-12 07:19 UTC, vlad-demchuk approved these changes

2025-12-17 21:34 UTC, closed without merging