solution 2/3
mate-academy/react_todo-app-add-and-delete pull request #276
Opened 2023-02-14 15:55 UTC by igor-kashchenko

[DEMO LINK](https://igor-kashchenko.github.io/react_todo-app-add-and-delete/)

2023-02-16 16:28 UTC, GarryRocksman approved these changes
GJ🔥

2023-02-16 16:28 UTC, GarryRocksman commented on src/App.tsx
> +  }, []);
Here am not sure that all requests goes at the same time, i use Promise.all in my code

2023-02-16 16:28 UTC, GarryRocksman commented on src/api/todos.ts
> +  return client.delete(`/todos/${todoId}?userId=${userId}`);
here you dont need user Id 
<img width="1068" alt="Screenshot 2023-02-16 at 18 26 22" src="https://user-images.githubusercontent.com/34283676/219426981-bfb3bb77-c487-41f2-a5c8-68bc833745ff.png">

2023-02-17 10:04 UTC, Anna-Tkachenko requested changes
check the behavior on adding todo: when I add new todo, the loader should be visible only in component with temporary todo, not for all existing todos

2023-02-17 10:04 UTC, Anna-Tkachenko commented on src/components/Notification/Notification.tsx
> +    setInterval(onClear, 3000);
do you need to clear this interval?

2023-02-21 17:35 UTC, denys-cheporniuk approved these changes

2024-11-08 14:13 UTC, closed without merging