Solution
mate-academy/react_todo-app-add-and-delete pull request #556
Opened 2023-07-03 12:28 UTC by bohdan-mykhailenko

[DEMO LINK](https://bohdan-mykhailenko.github.io/react_todo-app-add-and-delete/)

2023-07-03 15:15 UTC, serentinos approved these changes
Good job!

2023-07-03 19:34 UTC, silchyn requested changes
Should todos be completed initially?

2023-07-04 07:55 UTC, bohdan-mykhailenko commented
> Should todos be completed initially?

I just set it for testing 'Clear completed' button

2023-07-04 07:56 UTC, bohdan-mykhailenko commented
> Should todos be completed initially?

2023-07-04 08:19 UTC, bohdan-mykhailenko commented on src/components/TodoFilter/TodoFilter.tsx
> +});
Good point
Here we go

const filterStatuses = Object
    .keys(FilterStatus) as (keyof typeof FilterStatus)[];

  return (
    <nav className="filter">
      {filterStatuses.map(status => (
        <Fragment key={status}>
          <a
            href={status !== 'all' ? `#/${status}` : '#/'}
            className={cn('filter__link', {
              selected: status === filterStatus,
            })}
            onClick={event => handleFilterClick(event, FilterStatus[status])}
          >
            {status}
          </a>
        </Fragment>
      ))}
    </nav>
  );
});

2023-07-05 11:40 UTC, silchyn requested changes
Split logic into components

2023-07-05 11:40 UTC, silchyn commented on src/App.tsx
> +  const [filterStatus, setFilterStatus] = useState(FilterStatus.all);
```suggestion
  const [statusFilter, setStatusFilter] = useState(FilterStatus.all);
```

2023-07-05 11:40 UTC, silchyn commented on src/App.tsx
> +  const [isFetching, setIsFetching] = useState(false);
```suggestion
  const [isLoading, setIsLoading] = useState(false);
```

2023-07-05 11:40 UTC, silchyn commented on src/App.tsx
> +  const [isFetching, setIsFetching] = useState(false);
What is fetching?

2023-07-05 11:40 UTC, silchyn commented on src/App.tsx
> +  const [loadingTodoIds, setLoadingTodoIds] = useState([0]);
Where this `0` comes from?

2023-07-05 11:40 UTC, silchyn commented on src/App.tsx
> +      .then(todosFromServer => setTodos(todosFromServer))
```suggestion
      .then(setTodos)
```

2023-07-05 11:40 UTC, silchyn commented on src/App.tsx
> +  const isTodosVisible = todosCount > 0;
```suggestion
  const areTodosVisible = todosCount > 0;
```

2023-07-05 11:40 UTC, silchyn commented on src/App.tsx
> +  }, [todos, filterStatus]);
```suggestion
  const visibleTodos = useMemo(() => (
    getFilteredTodos(todos, filterStatus);
  ), [todos, filterStatus]);
```

2023-07-05 11:40 UTC, silchyn commented on src/App.tsx
> +  const isSomeActiveTodos = todosCount - completedTodos.length > 0;
```suggestion
  const hasActiveTodos = todosCount - completedTodos.length > 0;
```

2023-07-05 11:40 UTC, silchyn commented on src/App.tsx
> +  const isSomeActiveTodos = todosCount - completedTodos.length > 0;
What if new status occurs?

2023-07-06 10:51 UTC, silchyn approved these changes
The next part of this task will be reviewed

2024-08-02 21:43 UTC, closed without merging