sol
mate-academy/react_todo-app-add-and-delete pull request #621
Opened 2023-07-26 07:15 UTC by yurii-krymskiy

[DEMO LINK](https://yurii-krymskiy.github.io/react_todo-app-add-and-delete/)

2023-07-26 15:23 UTC, mykhalenych requested changes

2023-07-26 15:23 UTC, mykhalenych commented on src/App.tsx
> +  const handleInput = (event: any) => {
don't use any in typescript, add types

2023-07-26 15:23 UTC, mykhalenych commented on src/App.tsx
> +  const handleSubmit = async (event: any) => {
check all any

2023-07-26 15:23 UTC, mykhalenych commented on src/App.tsx
> +        setErrorMessage(Error.Adding);
why do you set two messages?

2023-07-26 15:23 UTC, mykhalenych commented on src/App.tsx
> +      setErrorMessage(Error.Deleting);
the same

2023-07-26 15:23 UTC, mykhalenych commented on src/components/Notification.tsx
> +    if (showNotification) {
it is reduntand state you can check if(errorMessage !== Error.NoError)

2023-07-26 15:23 UTC, mykhalenych commented on src/components/Notification.tsx
> +        setShowNotification(false);
and set default error message

2023-07-26 15:23 UTC, mykhalenych commented on src/components/Notification.tsx
> +    } return;
```suggestion
    }
```

2023-07-26 15:23 UTC, mykhalenych commented on src/components/Notification.tsx
> +  return showNotification ? (
```suggestion
  return showNotification && (
```

2023-07-26 15:23 UTC, mykhalenych commented on src/components/Notification.tsx
> +  ) : (
```suggestion
  )
```

2023-07-27 09:58 UTC, volodymyr-soltys97 requested changes
Let's improve your code

2023-07-27 09:58 UTC, volodymyr-soltys97 commented on src/App.tsx
> +    console.log(tempTodo);
Do you need `console.log()` here?

2023-07-27 13:51 UTC, mykhalenych requested changes

2023-07-27 13:51 UTC, mykhalenych commented on src/App.tsx
> +  const [showNotification, setShowNotification] = useState<boolean>(false);
delete this state, and check if errorMessage === Error.NoError, and when you need to clear state use setErrorMessage(Error.NoError)

2023-07-27 14:30 UTC, closed without merging